'use strict';
const $=id=>document.getElementById(id), num=id=>Number($(id).value), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let plans=[],runs=[],editId=null,selectedId=null,view='home',live=[],lastSample=null,lastRecording=false,reviewRows=[],pairedRows=[],derived={},reviewMeta={},aggregateRows=[],profileLoaded=false,lastHardware=null,scripts=[];
const colors=['#28685e','#a76b31','#416993','#a34d67'];
let subsetDirty=false;
let batchState={state:'idle',items:[]},currentPhase='idle',rippleResults={rows:[],excluded:[]};
async function get(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function send(action,values={}){const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...values})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function bind(id,fn){$(id).addEventListener('click',async()=>{const b=$(id);b.disabled=true;$('error').textContent='';try{await fn()}catch(e){$('error').textContent=e.message}finally{b.disabled=false}})}
function say(text){$('message').textContent=text}
function show(name){if(!$('view-'+name))name='home';view=name;document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===name)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});history.replaceState(null,'','#'+name);document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+name);if(['live','connections','troubleshoot','dashboard','plan'].includes(name))readiness().catch(showError);if(name==='plan')loadCsvColumns().catch(showError);if(name==='scripts')loadScripts().catch(showError);if(name==='review'){refreshRuns().catch(showError);loadResults().catch(showError)}if(name==='compare')aggregate().catch(showError);if(name==='configuration')loadRegistry().then(()=>lastHardware&&renderConfiguration(lastHardware)).catch(showError);window.scrollTo(0,0);drawAll()}
function showError(e){$('error').textContent=e.message}
// The menu uses native anchor links, including keyboard navigation and deep links.
window.addEventListener('hashchange',()=>show(location.hash.slice(1)));
function planForm(){return {test_id:$('plan-testid').value.trim(),method:$('plan-method').value,test_type:$('plan-type').value,rpm:num('plan-rpm'),load:num('plan-load'),load_unit:$('plan-load-unit').value,repeat:num('plan-repeat'),duration_s:num('plan-duration'),settle_rpm:num('plan-tolerance'),settle_load:num('plan-load-tolerance'),settle_s:num('plan-hold'),capture_rate_hz:$('plan-rate').value===''?null:num('plan-rate'),notes:$('plan-notes').value,capture_high_rate:$('plan-capture').checked}}
function fillPlan(p){editId=p.id;$('plan-capture').checked=p.capture_high_rate===true;$('edit-title').textContent='Edit planned run';for(const [id,key]of [['plan-testid','test_id'],['plan-method','method'],['plan-type','test_type'],['plan-rpm','rpm'],['plan-load','load'],['plan-load-unit','load_unit'],['plan-repeat','repeat'],['plan-duration','duration_s'],['plan-tolerance','settle_rpm'],['plan-load-tolerance','settle_load'],['plan-hold','settle_s'],['plan-rate','capture_rate_hz'],['plan-notes','notes']])$(id).value=p[key]??''}
function renderPlans(){const filter=$('plan-filter').value;const counts={};plans.forEach(p=>counts[p.status]=(counts[p.status]||0)+1);$('plan-counts').textContent=plans.length+' planned · '+Object.entries(counts).map(([k,n])=>n+' '+k).join(' · ');$('plan-table').innerHTML=plans.filter(p=>filter==='all'||p.status===filter).map(p=>`<tr class="${p.id===selectedId?'selected-row':''}"><td><input type="checkbox" data-plan="${esc(p.id)}" aria-label="Include ${esc(p.test_id||p.id)}" ${p.selected?'checked':''}></td><td title="${esc(p.id)}">${esc(p.test_id||p.id.slice(-8))}</td><td>${esc(p.method)}</td><td>${p.rpm.toFixed(1)}</td><td>${esc(loadText(p))}</td><td>${esc(p.test_type)}</td><td>${p.repeat}</td><td><span class="pill">${esc(pointStatus(p))}</span><br>${esc(p.reason)}</td><td><button data-use="${esc(p.id)}">Select</button><button data-edit="${esc(p.id)}">Edit</button></td></tr>`).join('')}
async function refreshPlans(){const incoming=await get('/api/plans');if(subsetDirty)for(const p of incoming){const old=plans.find(o=>o.id===p.id);if(old)p.selected=old.selected}plans=incoming;renderPlans();renderMatrix()}
$('plan-filter').addEventListener('change',renderPlans);
$('plan-table').addEventListener('change',e=>{if(e.target.dataset.plan){const p=plans.find(p=>p.id===e.target.dataset.plan);p.selected=e.target.checked;subsetDirty=true;renderMatrix()}});
$('plan-table').addEventListener('click',async e=>{try{if(e.target.dataset.edit){fillPlan(plans.find(p=>p.id===e.target.dataset.edit));window.scrollTo(0,0)}if(e.target.dataset.use){const p=await send('select',{id:e.target.dataset.use});selectedId=p.id;setManual(p);renderPlans();renderMatrix();showSelected();say('Point selected. Run selected test starts this point when board checks pass.')}}catch(err){showError(err)}});
bind('new-plan',()=>{editId=null;$('edit-title').textContent='Add a test';say('Next save adds a new plan.')});
bind('save-plan',async()=>{await send('plan',{...planForm(),...(editId?{id:editId}:{})});await refreshPlans();say('Test saved. Select it to check readiness.')});
bind('generate',async()=>{const result=await send('matrix',{...planForm(),test_id:'',test_type:'steady state',speed_base:num('speed-base'),load_base:num('load-base'),load_unit:$('load-base-unit').value,speeds:$('speed-fractions').value.split(',').map(Number),loads:$('load-fractions').value.split(',').map(Number)});await refreshPlans();say(`${result.created} paired plans added. Exclude infeasible points before running.`)});
bind('select-visible',()=>{const f=$('plan-filter').value;plans.forEach(p=>{if(f==='all'||p.status===f)p.selected=true});subsetDirty=true;renderPlans();renderMatrix()});
bind('clear-subset',()=>{plans.forEach(p=>p.selected=false);subsetDirty=true;renderPlans();renderMatrix()});
bind('save-subset',async()=>{await send('subset',{ids:plans.filter(p=>p.selected).map(p=>p.id)});subsetDirty=false;say('Subset saved.')});
bind('skip-selected',async()=>{await send('skip',{ids:plans.filter(p=>p.selected).map(p=>p.id),reason:$('skip-reason').value});await refreshPlans();say('Skipped plans retained with their reasons.')});
function showChecks(checks){return checks.map(c=>`<div class="quality-item"><strong>${esc(c.name)}</strong> <span class="${esc(c.state)}">${esc(c.state)}</span><br><small>${esc(c.detail)}</small>${c.state!=='pass'&&c.link?` <a href="${esc(c.link)}">Open settings</a>`:''}</div>`).join('')}
async function readiness(){const r=await get('/api/readiness');$('readiness').innerHTML=showChecks(r.checks);$('plan-readiness').innerHTML=showChecks(r.checks);$('connection-readiness').innerHTML=showChecks(r.hardware.readiness);$('hardware-report').textContent=JSON.stringify(r.hardware,null,2);renderTroubleshooting(r.hardware);return r}
bind('check-ready',readiness);
bind('apply',async()=>{await send('start',{rpm:num('rpm'),load:num('load'),load_unit:$('load-unit').value,mode:$('mode').value});say('Start / apply accepted. Watch both board states; the load is applied once the test motor is up to speed.')});
for(const id of ['stop','global-stop'])bind(id,async()=>{await send('stop');await refreshPlans();say('Coast stop requested on both boards. Check their reported states.')});
bind('run-test',async()=>{if(!selectedId)throw Error('Select a pending point from the test matrix first.');await send('run_test',{id:selectedId});show('plan');say('Selected-point workflow started: settle, record, then coast stop.')});
bind('record',async()=>{await send('record',{allow_unsettled:$('unsettled').checked});await refreshPlans();say('Recording started. It continues independently of this browser.')});
bind('finish',async()=>{await send('end_record');await refreshPlans();await refreshRuns();say('Recording finished; review the acquisition before accepting it.')});

const profileFields={'test-serial':'test_serial','load-serial':'load_serial','max-speed':'max_speed_rpm','max-load':'max_load_a','test-direction':'test_direction','load-direction':'load_direction','poll-rate':'polling_hz','stop-policy':'stop_policy','roles-verified':'roles_verified','units-verified':'axis_units_verified','stop-verified':'stop_policy_verified','sensorless-verified':'sensorless_startup_verified','sensorless-min':'sensorless_min_rpm','encoder-path':'encoder_reference_path','encoder-scale':'encoder_reference_scale_rad','encoder-speed-path':'encoder_speed_path','encoder-speed-scale':'encoder_speed_scale_rpm','encoder-verified':'encoder_reference_verified','capture-bandwidth':'capture_bandwidth_hz','capture-filtering':'capture_filtering','coupling-ratio':'coupling_ratio','coupling-sign':'coupling_sign','coupling-verified':'coupling_verified','handover-tol':'handover_tolerance_rpm','handover-hold':'handover_hold_s'};
const numericProfile=new Set(['coupling-ratio','coupling-sign','handover-tol','handover-hold','max-speed','max-load','test-direction','load-direction','poll-rate','sensorless-min','encoder-scale','encoder-speed-scale','capture-bandwidth']);
function fillProfile(p){for(const [id,key] of Object.entries(profileFields)){const el=$(id);if(el.type==='checkbox')el.checked=p[key]===true;else el.value=p[key]??''}profileLoaded=true}
function readProfile(){const p={};for(const [id,key] of Object.entries(profileFields)){const el=$(id);p[key]=el.type==='checkbox'?el.checked:numericProfile.has(id)?(el.value.trim()===''?null:Number(el.value)):el.value.trim()}return p}
bind('save-connection',async()=>{const h=await send('configure_connection',{profile:readProfile()});fillProfile(h.profile);say('Connection profile saved. No board configuration was written.');await readiness()});
bind('connect',async()=>{await send('connect');live=[];lastSample=null;await readiness();say('Boards connected for read-only monitoring. Motion requires Start or Run selected test.')});
bind('disconnect',async()=>{await send('disconnect');live=[];lastSample=null;drawLive();await readiness();say('Board connections released.')});
bind('clear-errors',async()=>{await send('clear_errors');await readiness();say('Error-clear command sent. Check reported board errors before starting.')});
async function loadScripts(){if(!scripts.length){scripts=await get('/api/scripts');$('script-select').innerHTML=scripts.map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join('')}await chooseScript()}
async function chooseScript(){const name=$('script-select').value;if(!name)return;const script=await get('/api/script?name='+encodeURIComponent(name));if($('script-select').value!==name)return;$('script-code').textContent=script.content;$('script-description').textContent=scripts.find(s=>s.name===name)?.description||''}
$('script-select').addEventListener('change',()=>chooseScript().catch(showError));
bind('copy-script',async()=>{await navigator.clipboard.writeText($('script-code').textContent);say('Script copied.')});

const liveSpecs=[{id:'voltage',title:'DC bus voltage · V',lines:[['dc_voltage_v','Voltage']],span:1},
{id:'current',title:'DC bus current · A (board estimate)',lines:[['dc_current_a','Current']],span:.2},
{id:'speed',title:'Rotor speed · rpm',lines:[['speed_rpm','Speed']],span:20},
{id:'position',title:'Rotor position · mechanical revolutions from displayed zero',lines:[['position_revolutions','Position']],span:1},
{id:'torque',title:'Estimated torque · N·m (estimate, not measured)',lines:[['torque_display_nm','Estimate']],span:.05},
{id:'phases',title:'Phase currents A / B / C · A (polled samples, not high-rate)',lines:[['ia_a','Phase A'],['ib_a','Phase B'],['ic_a','Phase C']],span:.2}];
let monitorPaused=false;
function monitorCards(role){$(role+'-live-charts').innerHTML=liveSpecs.map(s=>`<article class="panel" data-graph-card="${s.id}"><h2>${s.title}</h2><div class="legend">${s.lines.map(([key,label],i)=>`<span style="color:${colors[i]}">${label} <b id="${role}-${s.id}-${i}" class="metric-value"></b></span>`).join('')}</div><canvas id="${role}-${s.id}" aria-label="${s.title}"></canvas></article>`).join('')}
for(const role of ['test','load'])monitorCards(role);
const reviewSpecs=[{id:'angle',title:'Electrical-angle error · deg',keys:['angle_error_deg'],labels:['Estimated − independent reference'],span:1},
{id:'phase',title:'Phase currents · A',keys:['ia_a','ib_a','ic_a'],labels:['Ia','Ib','Ic'],span:.2},
{id:'dq',title:'Id / Iq · A',keys:['drive_id_a','drive_iq_a','id_reference_a','iq_reference_a'],labels:['Controller Id','Controller Iq','Encoder-reference Id','Encoder-reference Iq'],span:.2},
{id:'rpm',title:'Speed · rpm',keys:['encoder_rpm','command_rpm','estimated_rpm'],labels:['Independent encoder','Command','Estimator'],span:100},
{id:'bus',title:'DC bus voltage · V',keys:['drive_dc_voltage_v','load_dc_voltage_v'],labels:['Test','Load'],span:1},
{id:'branch',title:'Branch DC current · A',keys:['drive_dc_current_a','load_dc_current_a'],labels:['Test','Load'],span:.2}];
function chartCards(container,specs,prefix){$(container).innerHTML=specs.map(s=>`<article class="panel"><h2>${s.title}</h2><div class="legend">${s.labels.map((l,i)=>`<span style="color:${colors[i]}">${l} <b id="${prefix}-${s.id}-${i}" class="metric-value"></b></span>`).join('')}</div><canvas id="${prefix}-${s.id}" aria-label="${s.title}"></canvas></article>`).join('')}
chartCards('review-charts',reviewSpecs,'review');
function chart(id,series,minSpan,range,windowRange,xUnit='s'){const c=$(id);if(!c||c.clientWidth<1)return;const g=c.getContext('2d'),w=c.clientWidth,h=240,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;g.setTransform(dpr,0,0,dpr,0,0);const left=62,right=w-(xUnit==='rpm'?40:12),top=16,bottom=h-32;let values=[];for(const s of series)for(const p of s.points)if(Number.isFinite(p.y))values.push(p.y);if(!values.length){g.fillStyle='#63665f';g.font='14px system-ui';g.fillText('Channel unavailable in this dataset',15,100);return}let low=values.reduce((a,b)=>Math.min(a,b),Infinity),high=values.reduce((a,b)=>Math.max(a,b),-Infinity),span=Math.max(minSpan,high-low),mid=(high+low)/2;low=mid-span*.6;high=mid+span*.6;let lo=range[0],hi=range[1];if(hi<=lo)hi=lo+1;const x=t=>left+(t-lo)/(hi-lo)*(right-left),y=v=>bottom-(v-low)/(high-low)*(bottom-top);g.font='11px system-ui';g.textAlign='right';g.fillStyle='#63665f';for(let i=0;i<=4;i++){let v=low+(high-low)*i/4,py=y(v);g.strokeStyle='#deddd2';g.beginPath();g.moveTo(left,py);g.lineTo(right,py);g.stroke();g.fillText(Math.abs(v)>=100?v.toFixed(0):v.toFixed(2),left-8,py+4)}g.textAlign='center';for(let i=0;i<=3;i++){const t=lo+(hi-lo)*i/3;g.fillText((xUnit==='rpm'?t.toFixed(0):t.toFixed(2))+' '+xUnit,x(t),bottom+22)}g.save();g.beginPath();g.rect(left,top,right-left,bottom-top);g.clip();if(windowRange){g.fillStyle='#79e3bc13';g.fillRect(x(windowRange[0]),top,x(windowRange[1])-x(windowRange[0]),bottom-top);g.strokeStyle='#28685e';for(const t of windowRange){g.beginPath();g.moveTo(x(t),top);g.lineTo(x(t),bottom);g.stroke()}}
for(const s of series){g.strokeStyle=s.color;g.lineWidth=1.6;g.setLineDash(s.dash||[]);g.beginPath();let last=null;const dt=s.points.length>1?(s.points[s.points.length-1].t-s.points[0].t)/(s.points.length-1):1;for(const p of s.points){if(!Number.isFinite(p.y)){last=null;continue}if(last!==null&&p.t-last<Math.max(dt*2.5,.0001))g.lineTo(x(p.t),y(p.y));else g.moveTo(x(p.t),y(p.y));last=p.t}g.stroke();if(s.markers){g.setLineDash([]);g.fillStyle=s.color;for(const p of s.points)if(Number.isFinite(p.y)){g.beginPath();g.arc(x(p.t),y(p.y),3.5,0,Math.PI*2);g.fill()}}}g.restore()}
function drawLive(){if(monitorPaused)return;const windowS=Number($('mon-window').value)||30;const end=live.length?live[live.length-1].time_s:0;const recent=live.filter(r=>end-r.time_s<=windowS);
 for(const role of ['test','load'])for(const spec of liveSpecs){const board=lastHardware?.boards[role];const series=spec.lines.map(([key],i)=>({color:colors[i],points:recent.map(r=>({t:r.time_s-end,y:r[role]?.[key]}))}));chart(role+'-'+spec.id,series,spec.span,[-windowS,0]);
  spec.lines.forEach(([key],i)=>{const value=board?.connected?(key==='torque_display_nm'?(board.signals.torque_estimate_nm??board.signals.torque_nm):board.signals[key]):null;const label=$(role+'-'+spec.id+'-'+i);label.textContent=Number.isFinite(value)?value.toFixed(3):'Unavailable'})}}
function drawReview(){if(!reviewRows.length)return;const t=reviewRows.map(r=>r.time_s);for(const spec of reviewSpecs){const series=spec.keys.map((key,i)=>({color:colors[i],points:derived[key]?derived.time_s.map((x,j)=>({t:x,y:derived[key][j]})):reviewRows.map(r=>({t:r.time_s,y:r[key]}))}));if(pairedRows.length){const offset=reviewRows[0].time_s-pairedRows[0].time_s;spec.keys.forEach((key,i)=>series.push({color:colors[i],dash:[5,5],points:pairedRows.map(r=>({t:r.time_s+offset,y:r[key]}))}))}chart('review-'+spec.id,series,spec.span,[t.reduce((a,b)=>Math.min(a,b),Infinity),t.reduce((a,b)=>Math.max(a,b),-Infinity)],[num('window-start'),num('window-end')])}}
bind('mon-pause',async()=>{monitorPaused=!monitorPaused;$('mon-pause').textContent=monitorPaused?'Resume display':'Pause display';if(!monitorPaused)drawLive();say(monitorPaused?'Display paused. Acquisition and recording continue.':'Display resumed.')});
$('mon-window').addEventListener('change',drawLive);
document.querySelectorAll('[data-graph]').forEach(box=>box.addEventListener('change',()=>{document.querySelectorAll(`[data-graph-card="${box.dataset.graph}"]`).forEach(card=>card.hidden=!box.checked);drawLive()}));
function drawAll(){if(view==='live')drawLive();if(view==='dashboard')drawDashboard();if(view==='review'){drawReview();drawRipple()}}
window.addEventListener('resize',drawAll);for(const id of ['window-start','window-end'])$(id).addEventListener('input',drawReview);

async function refreshRuns(){runs=await get('/api/runs');const old=$('review-run').value;$('review-run').innerHTML=runs.map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(-8))} · ${esc(r.plan.method)} · ${r.plan.rpm} rpm / ${r.plan.load_a} A · repeat ${r.plan.repeat} · ${esc(r.status)}</option>`).join('');if(runs.some(r=>r.id===old))$('review-run').value=old;await chooseRun()}
async function chooseRun(){const id=$('review-run').value;if(!id)return;const run=await get('/api/run?id='+encodeURIComponent(id));const old=$('review-dataset').value;$('review-dataset').innerHTML='<option value="telemetry">Continuous telemetry</option>'+run.datasets.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');$('review-dataset').value=run.datasets.includes(old)?old:(run.datasets[0]||'telemetry');$('run-metadata').textContent=JSON.stringify(run,null,2);$('download').href='/download?id='+encodeURIComponent(id);$('paired-run').innerHTML='<option value="">None</option>'+runs.filter(r=>r.id!==id&&r.plan.rpm===run.plan.rpm&&r.plan.load_a===run.plan.load_a&&r.plan.repeat===run.plan.repeat&&r.plan.method!==run.plan.method&&r.plan.test_type===run.plan.test_type&&r.status!=='recording').map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(-8))} · ${esc(r.plan.method)} · ${esc(r.source)}</option>`).join('');$('window-type').value=run.plan.test_type==='steady state'?'steady state':'transient';if(run.latest_review)renderResult(run.latest_review.summary);else{$('quality').textContent='No analysis yet.';$('metrics').innerHTML=''}reviewRows=[];pairedRows=[];derived={};for(const s of reviewSpecs){const c=$('review-'+s.id);c.getContext('2d').clearRect(0,0,c.width,c.height)}}
$('review-run').addEventListener('change',()=>chooseRun().catch(showError));bind('refresh-runs',refreshRuns);
async function loadData(){const data=await get('/api/data?id='+encodeURIComponent($('review-run').value)+'&dataset='+encodeURIComponent($('review-dataset').value));reviewRows=data.rows;reviewMeta=data.metadata;pairedRows=[];derived={};if(!reviewRows.length)throw Error('Dataset is empty.');$('window-start').value=reviewRows[0].time_s;$('window-end').value=reviewRows[reviewRows.length-1].time_s;$('dataset-info').textContent=`${data.original_samples} raw samples · display every ${data.display_stride} sample(s) · ${data.metadata.source} · ${data.metadata.acquisition.source}. Time is this dataset's original clock.`;$('overlay-info').textContent='Overlay clocks are not assumed synchronized.';drawReview()}
bind('load-data',loadData);
function settings(){return {start_s:num('window-start'),end_s:num('window-end'),window_type:$('window-type').value,max_timing_angle_deg:num('timing-budget'),...($('fundamental').value?{fundamental_hz:num('fundamental')}:{})}}
function renderResult(result){$('quality').innerHTML=`<p class="${result.valid_acquisition?'pass':'error'}">${result.valid_acquisition?'Acquisition checks passed for this window':'Acquisition checks failed or insufficient data'}</p>`+(result.quality_flags||[]).map(f=>`<div class="quality-item ${esc(f.severity)}">${esc(f.message)}</div>`).join('');const timing=result.timing||{};$('metrics').innerHTML=`<tr><th>Actual mean sample rate</th><td>${timing.actual_mean_hz?.toFixed(2)??'unavailable'} Hz</td></tr><tr><th>Timing gaps</th><td>${timing.gap_count??'unavailable'}</td></tr>`+Object.entries(result.metrics||{}).map(([key,val])=>`<tr><th>${esc(key)}</th><td>${esc(typeof val==='object'?JSON.stringify(val):val)}</td></tr>`).join('')}
bind('analyze',async()=>{const result=await send('review',{run_id:$('review-run').value,dataset:$('review-dataset').value,settings:settings()});renderResult(result);derived=result.derived||{};drawReview();say('Analysis saved as a new revision; raw data unchanged.')});
bind('overlay',async()=>{const id=$('paired-run').value;if(!id){pairedRows=[];drawReview();return}if(!reviewRows.length)throw Error('Load the primary dataset first.');const other=await get('/api/run?id='+encodeURIComponent(id));const dataset=$('review-dataset').value==='telemetry'?'telemetry':other.datasets.find(d=>d.startsWith('capture_'));if(!dataset)throw Error('Paired run has no matching capture type.');const data=await get('/api/data?id='+encodeURIComponent(id)+'&dataset='+encodeURIComponent(dataset));pairedRows=data.rows;$('overlay-info').textContent='Dashed: paired run, aligned by each dataset start for comparison only. This is not clock synchronization. Primary shaded window and metrics apply only to the primary run.';drawReview()});
bind('retry',async()=>{const p=await send('repeat',{run_id:$('review-run').value});await refreshPlans();selectedId=p.id;setManual(p);say('New attempt planned with the same repeat number. Earlier attempts remain intact.');show('dashboard')});
bind('save-note',async()=>{await send('note',{run_id:$('review-run').value,note:$('review-note').value});say('Note appended to the event log.')});
bind('accept',async()=>{await send('accept',{run_id:$('review-run').value,outcome:$('outcome').value,reason:$('review-note').value});await refreshPlans();await refreshRuns();say('Review saved. Next selected pending plan is ready for manual application.')});
$('mapping').value=JSON.stringify({time_s:{column:'Time',unit:'s',scale:1,offset:0,kind:'measured'},ia_a:{column:'Ia',unit:'A',scale:1,offset:0,kind:'measured'},ib_a:{column:'Ib',unit:'A',scale:1,offset:0,kind:'measured'},ic_a:{column:'Ic',unit:'A',scale:1,offset:0,kind:'measured'}},null,2);
$('import-meta').value=JSON.stringify({instrument:'',calibration_id:'',acquisition:{requested_hz:null,bandwidth_hz:null,filtering:'',anti_alias_verified:false,switching_hz:null,ranges:{},synchronization:{method:'',simultaneous:false,uncertainty_s:null}},calibration:{verified:false,id:'',pole_pairs:null,offset_rad:null,encoder_direction:1},independent_encoder_provenance:'',device_serials:{test:null,load:null},firmware:null},null,2);
bind('import',async()=>{const file=$('import-file').files[0];if(!file)throw Error('Choose a CSV file.');if(file.size>8000000)throw Error('CSV must be smaller than 8 MB.');const result=await send('import',{run_id:$('review-run').value,source:$('import-source').value,csv:await file.text(),mapping:JSON.parse($('mapping').value),metadata:JSON.parse($('import-meta').value)});await chooseRun();$('review-dataset').value=result.dataset;await loadData();say('Original CSV, normalized channels and provenance saved.')});
async function aggregate(){aggregateRows=await get('/api/aggregate?metric='+encodeURIComponent($('aggregate-metric').value));$('aggregate-table').innerHTML=aggregateRows.map((r,i)=>`<tr><td>${esc(r.source)}</td><td>${esc(r.method)}</td><td>${r.rpm}</td><td>${r.load_a}</td><td>${r.n}</td><td>${r.mean.toPrecision(5)}</td><td>${r.std===null?'Requires another repeat':r.std.toPrecision(4)}</td><td>${i+1}</td></tr>`).join('')||'<tr><td colspan="8">No compatible completed analyses for this metric.</td></tr>';const groups={};for(const r of aggregateRows){const key=JSON.stringify([r.source,r.method,r.test_type,r.group_signature]);(groups[key]??=[]).push(r)}let html='';for(const rows of Object.values(groups)){const speeds=[...new Set(rows.map(r=>r.rpm))].sort((a,b)=>a-b),loads=[...new Set(rows.map(r=>r.load_a))].sort((a,b)=>a-b);if(speeds.length<2||loads.length<2||rows.filter(r=>r.n>=2).length<4){html+=`<p>${esc(rows[0].source+' · '+rows[0].method)}: insufficient coverage for a map (need four cells with ≥2 independent repeats spanning two speeds and two loads).</p>`;continue}const max=Math.max(...rows.map(r=>r.mean),.000001);html+=`<div class="map table-wrap"><h3>${esc(rows[0].source+' · '+rows[0].method)}</h3><table><thead><tr><th>rpm / A</th>${loads.map(l=>`<th>${l} A</th>`).join('')}</tr></thead><tbody>${speeds.map(s=>`<tr><th>${s} rpm</th>${loads.map(l=>{const r=rows.find(r=>r.rpm===s&&r.load_a===l);return r&&r.n>=2?`<td style="background:rgba(66,160,133,${.1+.6*r.mean/max})">${r.mean.toPrecision(4)}<br><small>n=${r.n}</small></td>`:'<td>Insufficient data</td>'}).join('')}</tr>`).join('')}</tbody></table></div>`}$('maps').innerHTML=html||'<p>Maps appear after sufficient valid repeat coverage.</p>'}
bind('aggregate',aggregate);
function matrixState(p){return pointStatus(p)}
function renderMatrix(){
 const speeds=[...new Set(plans.map(p=>p.rpm))].sort((a,b)=>a-b);
 const loadKey=p=>`${p.load_unit||'A'}|${p.load??p.load_a}`;
 const loads=[...new Set(plans.map(loadKey))].sort((a,b)=>{const [ua,va]=a.split('|'),[ub,vb]=b.split('|');return ua===ub?Number(va)-Number(vb):ua<ub?1:-1});
 const loadHead=k=>{const [u,v]=k.split('|');return `${v} ${u==='Nm'?'N·m':'A'}`};
 const html=plans.length?`<table class="matrix-table"><thead><tr><th>Load ↓ / speed →</th>${speeds.map(s=>`<th>${s} rpm</th>`).join('')}</tr></thead><tbody>${loads.map(l=>`<tr><th>${loadHead(l)}</th>${speeds.map(s=>`<td><div class="matrix-cell">${plans.filter(p=>p.rpm===s&&loadKey(p)===l).map(p=>{const state=pointStatus(p);return `<button class="matrix-point method-${esc(p.method)} ${esc(state)} ${p.id===selectedId?'chosen':''} ${p.selected?'':'excluded'}" data-point="${esc(p.id)}" aria-pressed="${p.id===selectedId}" title="${esc((p.test_id||p.id)+' · '+p.method+' · repeat '+p.repeat+' · '+state)}"><strong>${p.method==='sensored'?'Sensored':'Sensorless'}</strong><span>${esc(p.test_id||'repeat '+p.repeat)}</span><span>${STATUS_ICON[state]||''} ${esc(state)}</span></button>`}).join('')}</div></td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty-state">No tests yet. Load a CSV in step 1, or open “Edit tests individually” below.</div>';
 if($('visual-matrix').innerHTML!==html)$('visual-matrix').innerHTML=html;
 const items=batchState.items||[],count=st=>items.filter(i=>pointStatus(plans.find(p=>p.id===i.id)||{id:i.id,status:''})===st).length;
 const done=items.filter(i=>['recorded','skipped','retried'].includes(i.state)).length;
 $('batch-progress').textContent=items.length?`${batchState.state.toUpperCase()} · ${count('completed')} completed · ${count('failed')} failed · ${count('skipped')} skipped · ${count('blocked')} blocked · ${count('pending')} pending of ${items.length}${batchState.reason?' · '+batchState.reason:''}${batchState.pause_requested?' · pausing after the current test':''}`:'Select a test tile, or run all included pending tests.';
 $('batch-meter').max=items.length||1;$('batch-meter').value=done;
 const current=plans.find(p=>p.id===batchState.current)||(['settling','capturing','recording','processing'].includes(currentPhase)?plans.find(p=>p.id===selectedId):null);
 $('current-test').textContent=current?`Current test: ${current.test_id||current.id.slice(-8)} · ${current.method} · ${current.rpm} rpm · ${loadText(current)} · ${pointStatus(current)}`:'No test running.';
 const reserved=['running','paused'].includes(batchState.state),sel=plans.find(p=>p.id===selectedId),selState=sel?pointStatus(sel):null;
 $('run-test').disabled=reserved||!(sel&&sel.status==='pending');
 $('run-all').disabled=reserved||!plans.some(p=>p.selected&&p.status==='pending');
 $('pause-batch').hidden=batchState.state!=='running';$('resume-batch').hidden=batchState.state!=='paused';$('cancel-batch').hidden=!reserved;
 $('retry-point').disabled=!(batchState.state==='paused'&&['failed','blocked'].includes(selState));
 $('skip-point').disabled=!sel||!['pending','failed','blocked'].includes(selState);showSelected();
}
$('visual-matrix').addEventListener('click',async e=>{const b=e.target.closest('[data-point]');if(!b)return;try{const p=await send('select',{id:b.dataset.point});selectedId=p.id;setManual(p);renderMatrix();renderPlans();say('Test selected. Click Run Selected Test to begin.')}catch(err){showError(err)}});
bind('run-all',async()=>{const ids=plans.filter(p=>p.selected&&p.status==='pending').map(p=>p.id);if(!ids.length)throw Error('Include at least one pending test.');batchState=await send('batch_start',{ids});renderMatrix();say('Batch started. It will pause if a point cannot run or a test fails.')});
bind('resume-batch',async()=>{batchState=await send('batch_resume');renderMatrix()});
bind('cancel-batch',async()=>{await send('batch_cancel');await refreshPlans();say('Sequence cancelled and Stop Both Motors requested (coast).')});
bind('zero-position',async()=>{await send('zero_position');live=[];lastSample=null;monitorPaused=false;$('mon-pause').textContent='Pause display';drawLive();say('Both displayed positions now start at zero. Raw board positions are retained in recordings.')});

async function loadResults(){rippleResults=await get('/api/results');renderRipple()}
function renderRipple(){
 const rows=rippleResults.rows||[];
 $('results-progress').textContent=`${rows.length} valid repeat results · ${(rippleResults.excluded||[]).length} excluded runs. ${rippleResults.note||''}`;
 $('results-exclusions').innerHTML=(rippleResults.excluded||[]).map(r=>`<p><strong>${esc(r.run_id.slice(-8))}</strong> · ${esc(r.reason)}</p>`).join('')||'<p>No excluded runs.</p>';
 $('results-table').innerHTML=rows.map(r=>`<tr><td>${esc(r.test_id||r.run_id.slice(-8))}</td><td>${esc(r.method)}</td><td>${r.rpm}</td><td>${esc(loadText(r))}</td><td>${r.repeat}</td><td>${Number.isFinite(r.raw_peak_to_peak)?r.raw_peak_to_peak.toPrecision(5):'Unavailable'}</td><td>${r.peak_to_peak.toPrecision(5)}</td><td>${r.accepted?'Accepted':'Awaiting acceptance'}</td></tr>`).join('');
 const groups=rippleGroups();
 $('ripple-charts').innerHTML=groups.length?groups.map((rows,i)=>`<article class="panel"><p class="eyebrow">LOAD ${esc(loadText(rows[0]))}</p><h2>Current ripple vs speed</h2><p class="small">${esc(rows[0].comparison.source||'Capture')} · ${esc(rows[0].comparison.sample_hz??rows[0].comparison.requested_hz??'?')} samples/s · bandwidth ${esc(rows[0].comparison.bandwidth_hz??'?')} Hz · acquisition group ${i+1}</p><div class="legend"><span style="color:${colors[0]}">● Sensored</span><span style="color:${colors[1]}">● Sensorless</span></div><p class="small" id="ripple-y-${i}"></p><canvas id="ripple-${i}" aria-label="Maximum current ripple in amperes against speed in rpm at load ${esc(loadText(rows[0]))}"></canvas><p class="small">${rows.length} valid repeats. Each point shows the largest value across repeats. Missing results remain gaps.</p></article>`).join(''):'<div class="empty-state">No valid phase-current results yet. Record steady-state captures, then click Process results. The exclusion list explains any missing points.</div>';
 drawRipple();
}
function rippleGroups(){const groups=new Map();for(const r of rippleResults.rows||[]){const key=JSON.stringify([r.load_unit||'A',r.load??r.load_a,r.comparison_key]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}return [...groups.values()].sort((a,b)=>(a[0].load_unit||'A').localeCompare(b[0].load_unit||'A')||(a[0].load??a[0].load_a)-(b[0].load??b[0].load_a))}
function drawRipple(){
 const metric=$('ripple-metric').value;
 $('results-definition').textContent=metric==='raw_peak_to_peak'?'Maximum raw peak-to-peak current · A: the largest (max − min) of the original phase A, B and C samples in the analysis window. It includes the fundamental, so it grows with load current and is not ripple on its own.':'Maximum peak-to-peak residual · A: DC and a least-squares fitted fundamental (speed × pole pairs) are removed separately from phases A, B and C, then the largest phase peak-to-peak is taken. Assumes a constant steady-state fundamental. Each plotted point is the maximum across valid repeats in the same acquisition group.';
 rippleGroups().forEach((rows,i)=>{
  const speeds=[...new Set([...rows.map(r=>r.rpm),...plans.filter(p=>(p.load??p.load_a)===(rows[0].load??rows[0].load_a)&&(p.load_unit||'A')===(rows[0].load_unit||'A')&&p.test_type==='steady state').map(p=>p.rpm)])].sort((a,b)=>a-b);
  const series=['sensored','sensorless'].map((method,j)=>({color:colors[j],markers:true,points:speeds.map(rpm=>{const vals=rows.filter(r=>r.method===method&&r.rpm===rpm).map(r=>r[metric]);return {t:rpm,y:vals.length?Math.max(...vals):null}})}));
  $('ripple-y-'+i).textContent=(metric==='raw_peak_to_peak'?'Maximum raw peak-to-peak':'Maximum residual peak-to-peak')+' · A';
  const lo=Math.min(...rows.map(r=>r.rpm)),hi=Math.max(...rows.map(r=>r.rpm)),pad=Math.max(1,(hi-lo)*.04);chart('ripple-'+i,series,.001,[lo-pad,hi+pad],null,'rpm');
 });
}
bind('process-results',async()=>{say('Processing original capture samples…');rippleResults=await send('process_results',{settings:{}});renderRipple();say('Results processed and saved. Both ripple measurements are available for export.')});
$('ripple-metric').addEventListener('change',drawRipple);
let settingsToken=null,troubleshootLoaded=false;
function invalidateSettings(){settingsToken=null;$('settings-preview').hidden=true}
function renderTroubleshooting(h,force=false){
 const p=h.profile,cfg=r=>h.boards[r].configuration||{},value=(v,u='')=>v===null||v===undefined?'unavailable':String(v)+u;
 const topics=[['Local rig limits','Set positive validated speed and load limits below. Zero deliberately disables motor commands.',`Speed: ${value(p.max_speed_rpm,' rpm')} · Load: ${value(p.max_load_a,' A')}`]];
 for(const role of ['test','load']){const c=cfg(role),title=role==='test'?'Test':'Load';topics.push([title+' watchdog','Enable the watchdog with a timeout compatible with the polling rate.',`Enabled: ${value(c['axis0.config.enable_watchdog'])} · Timeout: ${value(c['axis0.config.watchdog_timeout'],' s')}`]);topics.push([title+' controller mode',role==='test'?'Required: velocity control (2), velocity ramp (2), positive validated speed ramp.':'Required: torque control (1), torque ramp (6), positive validated torque ramp.',`Control mode: ${value(c['axis0.controller.config.control_mode'])} · Input mode: ${value(c['axis0.controller.config.input_mode'])}`])}
 $('troubleshoot-checks').innerHTML=topics.map(([name,help,current])=>{const check=h.readiness.find(c=>c.name===name);return `<article class="panel"><span class="pill ${esc(check?.state||'waiting')}">${esc(check?.state||'Connect to inspect')}</span><h3>${esc(name)}</h3><p>${esc(current)}</p><p>${esc(help)}</p></article>`}).join('');
 $('existing-limits').textContent=`Test board velocity limit: ${value(!Number.isFinite(cfg('test')['axis0.controller.config.vel_limit'])?null:cfg('test')['axis0.controller.config.vel_limit']*60,' rpm')} · Load board current limit: ${value(cfg('load')['axis0.config.motor.current_soft_max'],' A')}.`;
 const minimum=Math.max(.5,6/p.polling_hz);$('watchdog-range').textContent=`At ${p.polling_hz} Hz polling, the accepted timeout is ${minimum.toFixed(2)}–2.00 s.${minimum>2?' Increase polling to at least 3 Hz in Connections.':''}`;
 if(force||!troubleshootLoaded){$('fix-speed').value=p.max_speed_rpm||'';$('fix-load').value=p.max_load_a||'';for(const role of ['test','load']){const c=cfg(role);const timeout=c['axis0.config.watchdog_timeout'];$('fix-'+role+'-watchdog').value=Number.isFinite(timeout)&&timeout>=minimum&&timeout<=2?timeout:Math.max(1,minimum);$('fix-'+role+'-ramp').value=role==='test'?(c['axis0.controller.config.vel_ramp_rate']===undefined?'':c['axis0.controller.config.vel_ramp_rate']*60):(c['axis0.controller.config.torque_ramp_rate']??'')}troubleshootLoaded=true;}
 if(h.settings_result){$('settings-outcome').textContent=h.settings_result.state+(h.settings_result.error?' · '+h.settings_result.error:'');$('settings-report').textContent=JSON.stringify(h.settings_result,null,2)}
}
for(const id of ['fix-test-watchdog','fix-load-watchdog','fix-test-ramp','fix-load-ramp'])$(id).addEventListener('input',invalidateSettings);
bind('refresh-settings',async()=>{invalidateSettings();const h=await send('refresh_settings');renderTroubleshooting(h,true);await readiness();say('Current settings read from the connected boards.')});
bind('fix-limits',async()=>{const h=await send('update_limits',{max_speed_rpm:num('fix-speed'),max_load_a:num('fix-load')});fillProfile(h.profile);invalidateSettings();await readiness();say('Local rig limits saved. Board current and voltage limits were not changed.')});
bind('preview-settings',async()=>{invalidateSettings();const h=await send('preview_settings',{values:{test_watchdog_s:num('fix-test-watchdog'),load_watchdog_s:num('fix-load-watchdog'),test_ramp_rpm_s:num('fix-test-ramp'),load_ramp_nm_s:num('fix-load-ramp')}});settingsToken=h.settings_preview.token;$('settings-changes').innerHTML=h.settings_preview.changes.map(c=>`<tr><td>${esc(c.role)}<br>${esc(c.serial)}</td><td>${esc(c.path)}</td><td>${esc(c.before)}</td><td>${esc(c.after)}</td></tr>`).join('');$('settings-preview').hidden=false;$('persist-settings').checked=false;say('Preview ready. Review the board identities and proposed values before Apply.')});
bind('apply-settings',async()=>{if(!settingsToken)throw Error('Preview the changes first.');const token=settingsToken;invalidateSettings();try{const h=await send('apply_settings',{token,persist:$('persist-settings').checked});renderTroubleshooting(h,true);say('Settings update finished. Check the verified changes and remaining blockers.')}finally{await readiness()}});
// ---- Dashboard, Configuration and Test Matrix helpers ----
// Enum names from the ODrive 0.6.12 API reference / installed odrive package (odrive/enums.py).
const CONTROL_MODES={0:'VOLTAGE_CONTROL',1:'TORQUE_CONTROL',2:'VELOCITY_CONTROL',3:'POSITION_CONTROL'};
const INPUT_MODES={0:'INACTIVE',1:'PASSTHROUGH',2:'VEL_RAMP',3:'POS_FILTER',4:'MIX_CHANNELS',5:'TRAP_TRAJ',6:'TORQUE_RAMP',7:'MIRROR',8:'TUNING'};
const ROLE_NAME={test:'Test motor',load:'Load motor'};
function named(map,v){return v===null||v===undefined?'Unavailable':`${map[v]??'code'} (${v})`}
function fmt(v,d=2,u=''){return Number.isFinite(v)?v.toFixed(d)+(u?' '+u:''):'Unavailable'}
function loadText(p){const v=p.load??p.load_a;return Number.isFinite(v)?`${v} ${(p.load_unit||'A')==='Nm'?'N·m':'A'}`:'Unavailable'}
function boardNumber(serial){if(!serial)return 'ODrive ?';const h=lastHardware||{};const list=[...new Set([...(h.discovered?.boards||[]).map(b=>b.serial),h.profile?.test_serial,h.profile?.load_serial].filter(Boolean))].sort();return 'ODrive '+(list.indexOf(serial)+1)}
function kvRows(rows){return rows.map(([k,v,alert])=>`<tr class="${alert?'alert':''}"><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}
function faultList(b){const f=b.faults||{};const items=[...(f.active||[]).map(e=>['Active',e]),...(f.disarm||[]).map(e=>['Disarm reason',e])];return items.length?`<ul class="faults">${items.map(([k,e])=>`<li><strong>${esc(k)}: ${esc(e.name)}</strong> — ${esc(e.explanation)} <a href="${esc(e.doc)}" target="_blank" rel="noopener">reference</a></li>`).join('')}</ul>`:(b.connected?'<p class="pass">No active faults.</p>':'<p>Unavailable (not connected).</p>')}
function setManual(p){$('mode').value=p.method;$('rpm').value=p.rpm;$('load').value=p.load??p.load_a;$('load-unit').value=p.load_unit||'A'}
function dashRows(b,fresh){const s=fresh&&b.connected?b.signals:{},c=b.configuration||{},e=b.errors||{};const faulted=[e.active_errors,e.disarm_reason].some(v=>v!==0&&v!==null&&v!==undefined);const vel=c['axis0.controller.config.control_mode']===2;
 return kvRows([['Board',`${boardNumber(b.serial)} · ${b.serial||'not assigned'} · firmware ${b.firmware||'Unavailable'}`],['Connection / axis state',b.connected?(fresh?b.state:'STALE DATA'):'DISCONNECTED',b.connected&&!fresh],['Feedback source',b.feedback_method||'Unavailable'],
 ['Control / input mode',named(CONTROL_MODES,c['axis0.controller.config.control_mode'])+' / '+named(INPUT_MODES,c['axis0.controller.config.input_mode'])],
 ['Speed: reference / measured',(vel?fmt(s.speed_setpoint_rpm??s.speed_command_rpm,1):'n/a (not velocity control)')+' / '+fmt(s.speed_rpm,1)+' rpm'],['Speed error',vel?fmt(s.speed_error_rpm,2,'rpm'):'n/a (not velocity control)'],
 ['Iq: reference / measured',fmt(s.iq_command_a,3)+' / '+fmt(s.iq_a,3)+' A'],['Iq tracking error',fmt(s.iq_error_a,3,'A')],['Id measured',fmt(s.id_a,3,'A')],
 ['Estimated torque: firmware / Kt × Iq',fmt(s.torque_estimate_nm,3)+' / '+fmt(s.torque_nm,3)+' N·m (estimates, not measured)'],['Selected-feedback position / speed',fmt(s.position_turns,3,'turn')+' / '+fmt(s.speed_rpm,1,'rpm')],
 ['Sensorless estimate: speed / electrical phase',fmt(s.sensorless_speed_rpm,1,'rpm')+' / '+fmt(s.estimated_electrical_rad,2,'rad')],
 ['DC bus: voltage / current',fmt(s.dc_voltage_v,2,'V')+' / '+fmt(s.dc_current_a,2,'A')],['DC input power (V × I) / motor electrical power',fmt(s.electrical_power_w,1,'W')+' / '+fmt(s.motor_electrical_power_w,1,'W')],
 ['Temperature: motor / controller',fmt(s.motor_temp_c,1,'°C')+' / '+fmt(s.controller_temp_c,1,'°C')],
 ['Active errors / disarm reason',`${e.active_errors??'Unavailable'} / ${e.disarm_reason??'Unavailable'}`,faulted],['Last procedure result',b.procedure?`${b.procedure.name} (${b.procedure.code})`:'Unavailable']])}
const dashSpecs=[
 {id:'speed',title:'Speed · rpm',span:20,lines:[['test','speed_setpoint_rpm','Test reference',0,[6,4]],['test','speed_rpm','Test measured',0],['load','speed_rpm','Load measured',1]]},
 {id:'speed-error',title:'Test-motor speed error · rpm',span:2,lines:[['test','speed_error_rpm','Test (reference − measured)',0]]},
 {id:'iq',title:'Iq reference and measured · A',span:.5,lines:[['test','iq_command_a','Test reference',0,[6,4]],['test','iq_a','Test measured',0],['load','iq_command_a','Load reference',1,[6,4]],['load','iq_a','Load measured',1]]},
 {id:'iq-error',title:'Iq tracking error · A',span:.1,lines:[['test','iq_error_a','Test',0],['load','iq_error_a','Load',1]]},
 {id:'id',title:'Id · A',span:.1,lines:[['test','id_a','Test',0],['load','id_a','Load',1]]},
 {id:'torque',title:'Estimated torque · N·m (Kt × Iq; estimate)',span:.05,lines:[['test','torque_nm','Test',0],['load','torque_nm','Load',1]]},
 {id:'vbus',title:'DC bus voltage · V',span:1,lines:[['test','dc_voltage_v','Test board',0],['load','dc_voltage_v','Load board',1]]},
 {id:'ibus',title:'DC bus current · A',span:.5,lines:[['test','dc_current_a','Test board',0],['load','dc_current_a','Load board',1]]},
 {id:'power',title:'DC input power (V × I) · W',span:5,lines:[['test','electrical_power_w','Test board',0],['load','electrical_power_w','Load board',1]]},
 {id:'temps',title:'Temperatures · °C',span:2,lines:[['test','motor_temp_c','Test motor',0],['test','controller_temp_c','Test controller',2],['load','motor_temp_c','Load motor',1],['load','controller_temp_c','Load controller',3]]}];
$('dash-charts').innerHTML=dashSpecs.map(s=>`<article class="panel"><h2>${s.title}</h2><div class="legend">${s.lines.map(([,,label,c,dash])=>`<span style="color:${colors[c]}">${dash?'- - ':'— '}${label}</span>`).join('')}</div><canvas id="dash-${s.id}" aria-label="${s.title}"></canvas></article>`).join('');
function drawDashboard(){const end=live.length?live[live.length-1].time_s:0;const recent=live.filter(r=>end-r.time_s<=30);for(const s of dashSpecs)chart('dash-'+s.id,s.lines.map(([role,key,,c,dash])=>({color:colors[c],dash,points:recent.map(r=>({t:r.time_s-end,y:r[role]?.[key]}))})),s.span,[-30,0])}
function renderDashboard(d,fresh){const h=d.hardware;
 $('dash-strip').textContent=`Hardware · controller ${d.state}${h.control_stage?' · '+h.control_stage:''} · ${d.recording?'RECORDING · '+fmt(d.recording_elapsed_s,1,'s')+' elapsed':'not recording'} · telemetry ${fresh?'age '+fmt(d.telemetry_age_s*1000,0,'ms'):'Unavailable'}`;
 for(const role of ['test','load'])$('dash-'+role).innerHTML=dashRows(h.boards[role],fresh);drawDashboard()}
bind('zero-load',async()=>{await send('start',{rpm:num('rpm'),load:0,load_unit:$('load-unit').value,mode:$('mode').value});$('load').value=0;say('Load set to zero; the test motor keeps its speed setpoint.')});

// ---- Configuration: allowlisted editor with preview/apply/save/verify ----
let registry=[],cfgWritten={test:new Set(),load:new Set()},cfgSaved={test:new Set(),load:new Set()},cfgToken=null;
async function loadRegistry(){if(!registry.length)registry=await get('/api/registry')}
function cfgValue(v,e){if(v===null||v===undefined)return 'Unavailable';if(e.kind==='enum')return named(e.choices,v);if(typeof v==='boolean')return v?'on':'off';if(typeof v==='number')return String(+v.toPrecision(6))+(e.unit?' '+e.unit:'')+(e.unit==='turn/s'?` (${+(v*60).toPrecision(6)} rpm)`:'');return String(v)}
function cfgInput(role,e){const attrs=`data-role="${role}" data-path="${esc(e.path)}" data-kind="${e.kind}" aria-label="New ${esc(e.label)}"`;
 if(e.kind==='enum')return `<select ${attrs}><option value="">no change</option>${Object.entries(e.choices).map(([k,v])=>`<option value="${esc(k)}">${esc(v)} (${esc(k)})</option>`).join('')}</select>`;
 if(e.kind==='bool')return `<select ${attrs}><option value="">no change</option><option value="true">on</option><option value="false">off</option></select>`;
 return `<input type="number" step="any" ${e.min!==null?`min="${e.min}"`:''} ${e.max!==null?`max="${e.max}"`:''} placeholder="no change" ${attrs}>`}
function cfgTag(role,path,input){if(input&&input.value!=='')return '<span class="tag tag-unsaved">Unsaved edit</span>';if(cfgSaved[role].has(path))return '<span class="tag tag-saved">Saved and verified</span>';if(cfgWritten[role].has(path))return '<span class="tag tag-written">Written, not saved</span>';return '<span class="tag tag-read">Read from board</span>'}
function renderCfgEditor(h){if(!registry.length)return;
 for(const role of ['test','load']){const b=h.boards[role],c=b.configuration||{};const container=$('cfg-'+role);
  $('cfg-'+role+'-title').textContent=`${ROLE_NAME[role]} · ${boardNumber(b.serial)} · ${b.serial||'serial not assigned'}`;
  if(!b.connected){container.innerHTML='<p>Connect this board on the <a href="#connections">Connections</a> page to read and edit its configuration.</p>';continue}
  if(container.dataset.serial===b.serial&&container.querySelector('input,select')){ // keep typed values; refresh read-back column and tags
   for(const e of registry){const cell=container.querySelector(`[data-read="${CSS.escape(e.path)}"]`),tag=container.querySelector(`[data-tag="${CSS.escape(e.path)}"]`);if(cell)cell.textContent=cfgValue(c[e.path],e);if(tag)tag.innerHTML=cfgTag(role,e.path,container.querySelector(`[data-path="${CSS.escape(e.path)}"]`))}continue}
  const groups=[...new Set(registry.map(e=>e.group))];container.dataset.serial=b.serial;
  container.innerHTML=groups.map(g=>`<h4 class="cfg-group">${esc(g)}</h4><div class="table-wrap"><table class="cfg-table"><thead><tr><th>Setting</th><th>On board</th><th>New value</th><th>Status</th></tr></thead><tbody>${registry.filter(e=>e.group===g).map(e=>`<tr><th>${esc(e.label)}${e.note?`<br><small>${esc(e.note)}</small>`:''}</th><td data-read="${esc(e.path)}">${esc(cfgValue(c[e.path],e))}</td><td>${c[e.path]===null||c[e.path]===undefined?'<small>Unavailable on this firmware</small>':cfgInput(role,e)}</td><td data-tag="${esc(e.path)}">${cfgTag(role,e.path,null)}</td></tr>`).join('')}</tbody></table></div>`).join('')}}
document.addEventListener('input',e=>{const el=e.target;if(el.dataset&&el.dataset.path&&el.dataset.role){const tag=el.closest('tr')?.querySelector('[data-tag]');if(tag)tag.innerHTML=cfgTag(el.dataset.role,el.dataset.path,el);cfgToken=null;$('cfg-preview-panel').hidden=true}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset&&el.dataset.path&&el.dataset.role){const tag=el.closest('tr')?.querySelector('[data-tag]');if(tag)tag.innerHTML=cfgTag(el.dataset.role,el.dataset.path,el);cfgToken=null;$('cfg-preview-panel').hidden=true}});
function cfgChanges(){const changes={};for(const el of document.querySelectorAll('#view-configuration [data-path][data-role]')){if(el.value==='')continue;const v=el.dataset.kind==='bool'?el.value==='true':Number(el.value);(changes[el.dataset.role]??={})[el.dataset.path]=v}return changes}
function showCfgPreview(h){const pv=h.settings_preview;cfgToken=pv.token;$('cfg-changes').innerHTML=pv.changes.map(c=>`<tr><td>${esc(ROLE_NAME[c.role])}<br>${esc(c.serial)} · ${esc(c.firmware||'?')}</td><td>${esc(c.label||c.path)}<br><small>${esc(c.path)}</small></td><td>${esc(c.before)} ${esc(c.unit||'')}</td><td><strong>${esc(c.after)} ${esc(c.unit||'')}</strong></td></tr>`).join('');$('cfg-persist').checked=false;$('cfg-preview-panel').hidden=false;$('cfg-preview-panel').scrollIntoView({block:'nearest'})}
function showCfgResult(h){const r=h.settings_result;if(!r)return;$('cfg-outcome').textContent=r.state+(r.error?' · '+r.error:'')+(r.mismatches?.length?` · ${r.mismatches.length} value(s) did not persist`:'');$('cfg-report').textContent=JSON.stringify(r,null,2);$('cfg-verify').hidden=!h.persist_pending}
bind('cfg-refresh',async()=>{await loadRegistry();const h=await send('refresh_settings');lastHardware=h;for(const r of ['test','load'])delete $('cfg-'+r).dataset.serial;renderConfiguration(h);say('Configuration read from the connected boards. Nothing was written.')});
bind('cfg-discard',async()=>{for(const r of ['test','load'])delete $('cfg-'+r).dataset.serial;cfgToken=null;$('cfg-preview-panel').hidden=true;if(lastHardware)renderConfiguration(lastHardware);say('Unsaved edits discarded.')});
bind('cfg-preview',async()=>{const changes=cfgChanges();if(!Object.keys(changes).length)throw Error('Enter at least one new value first.');showCfgPreview(await send('config_preview',{changes}));say('Check the board identities and every before/after value, then Apply.')});
bind('cfg-apply',async()=>{if(!cfgToken)throw Error('Preview the changes first.');const token=cfgToken,persist=$('cfg-persist').checked;cfgToken=null;$('cfg-preview-panel').hidden=true;
 try{const h=await send('apply_settings',{token,persist});lastHardware=h;const r=h.settings_result||{};for(const c of r.verified||[])cfgWritten[c.role].add(c.path);for(const r2 of ['test','load'])delete $('cfg-'+r2).dataset.serial;showCfgResult(h);renderConfiguration(h);
  say(persist?'Changes written, read back and saved. The boards reboot: wait for them, then click Reconnect and verify.':'Changes written and read back. They are not saved; a power cycle restores the previous values.')}
 finally{try{const h=await get('/api/status');showCfgResult(h.hardware)}catch(e){}}});
bind('cfg-verify',async()=>{const h=await send('verify_persisted');lastHardware=h;const r=h.settings_result||{};if(!r.mismatches?.length){for(const role of ['test','load'])for(const p of cfgWritten[role]){cfgSaved[role].add(p)}}for(const r2 of ['test','load'])delete $('cfg-'+r2).dataset.serial;showCfgResult(h);renderConfiguration(h);say(r.state||'Verification finished.')});
bind('cfg-clear-errors',async()=>{const h=await send('clear_errors');lastHardware=h;renderConfiguration(h);say('Clear-errors sent. Check the fault lists; clearing never restarts a motor.')});
bind('cfg-backup',async()=>{const h=await send('config_backup');const blob=new Blob([JSON.stringify(h.backup,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='odrive-backup-'+h.backup.created_utc.replace(/[:]/g,'')+'.json';a.click();URL.revokeObjectURL(a.href);say('Backup saved on this computer ('+h.backup_file+') and downloaded.')});
bind('cfg-restore',async()=>{const file=$('cfg-restore-file').files[0];if(!file)throw Error('Choose a backup file.');const backup=JSON.parse(await file.text());showCfgPreview(await send('config_restore_preview',{backup,allow_other_serial:$('cfg-restore-other').checked}));say('Restore preview ready. Review every value, then Apply.')});
function renderCalibration(h){const info=h.calibration_info;if(!info)return;const kind=$('cal-kind').value;$('cal-description').textContent=info.kinds[kind]?.description||'';
 if(!$('cal-checklist').dataset.ready){$('cal-checklist').innerHTML=info.checklist.map((t,i)=>`<label class="check"><input type="checkbox" data-cal="${i}">${esc(t)}</label>`).join('');$('cal-checklist').dataset.ready='1'}
 const c=h.calibration;$('cal-status').textContent=c?`${ROLE_NAME[c.role]} · ${c.state_name} · ${c.state.toUpperCase()} · ${c.detail}${c.result?' · result '+c.result.name+': '+c.result.explanation:''}`:'No calibration run in this session.';$('cal-status').className=c?.state==='succeeded'?'pass':c?.state==='running'?'waiting':c?'blocked':''}
$('cal-kind').addEventListener('change',()=>lastHardware&&renderCalibration(lastHardware));
bind('cal-start',async()=>{const confirmations=[...document.querySelectorAll('[data-cal]')].filter(x=>x.checked).map(x=>Number(x.dataset.cal));const role=$('cal-role').value,kind=$('cal-kind').value;
 const h=await send('calibrate',{role,kind,confirmations});lastHardware=h;renderCalibration(h);document.querySelectorAll('[data-cal]').forEach(x=>x.checked=false);say(`${ROLE_NAME[role]} calibration requested. Watch the motor; Stop Both Motors cancels it.`)});
function renderIdentity(h){for(const role of ['test','load']){const b=h.boards[role],c=b.configuration||{};const hw=[c.hw_version_major,c.hw_version_minor,c.hw_version_variant].every(v=>v!==null&&v!==undefined)?`${c.hw_version_major}.${c.hw_version_minor}.${c.hw_version_variant}`:'Unavailable';
 $('cfg-id-'+role).innerHTML=`<h3>${ROLE_NAME[role]}</h3><table class="kv"><tbody>${kvRows([['Board',`${boardNumber(b.serial)} · ${b.serial||'not assigned'}`],['Connection / axis state',b.connected?b.state:'DISCONNECTED'],['Firmware',(b.firmware||'Unavailable')+(b.firmware_unreleased?' (unreleased build)':'')],['Hardware version',hw],['Bootloader version',c.bootloader_version??'Unavailable'],['Reboot required',c.reboot_required===true?'yes: save and reboot to apply':c.reboot_required===false?'no':'Unavailable'],['Feedback source',b.feedback_method||'Unavailable'],['Last procedure result',b.procedure?`${b.procedure.name}: ${b.procedure.explanation}`:'Unavailable']])}</tbody></table>${faultList(b)}`}}
function renderConfiguration(h){const found=h.discovered;
 $('discovered').innerHTML=!found?'<p>No discovery run yet.</p>':!found.boards.length?`<p class="blocked">No ODrive found on USB (${esc(found.at_utc)}). Check power, cables and isolators, and that no other program owns the board.</p>`:
  `<div class="table-wrap"><table><thead><tr><th>Board</th><th>Serial number</th><th>Device</th><th>Assigned role</th><th>Assign</th></tr></thead><tbody>${found.boards.map(b=>`<tr><td>${esc(boardNumber(b.serial))}</td><td>${esc(b.serial)}${b.note?'<br><small>'+esc(b.note)+'</small>':''}</td><td>${esc(b.device_type)}</td><td>${esc(b.assigned_role?ROLE_NAME[b.assigned_role]:'unassigned')}</td><td><button data-assign="test" data-serial="${esc(b.serial)}">Use as Test Motor</button><button data-assign="load" data-serial="${esc(b.serial)}">Use as Load Motor</button></td></tr>`).join('')}</tbody></table></div><p class="small">${esc(found.at_utc)} · ${esc(found.method)}</p>`;
 renderIdentity(h);renderCfgEditor(h);renderCalibration(h);showCfgResult(h)}
$('discovered').addEventListener('click',async e=>{const b=e.target.closest('[data-assign]');if(!b)return;try{const role=b.dataset.assign,other=role==='test'?'load':'test',p=readProfile();if(p[other+'_serial']===b.dataset.serial)p[other+'_serial']='';p[role+'_serial']=b.dataset.serial;p.roles_verified=false;const h=await send('configure_connection',{profile:p});fillProfile(h.profile);lastHardware=h;renderConfiguration(h);say(`${ROLE_NAME[role]} assigned to ${b.dataset.serial} in the local profile. Nothing was written to a board. Re-confirm the physical roles on Connections.`)}catch(err){showError(err)}});
bind('discover',async()=>{const h=await send('discover',{window_s:2});lastHardware=h;renderConfiguration(h);say(`${h.discovered.boards.length} ODrive(s) found. No connection was opened.`)});

// ---- Test Matrix: CSV import, run controls, status mapping ----
let csvToken=null;
async function loadCsvColumns(){if($('csv-columns').dataset.ready)return;const cols=await get('/api/matrix-columns');$('csv-columns').innerHTML=cols.map(c=>`<tr><td><code>${esc(c.column)}</code></td><td>${esc(c.unit)}</td><td>${esc(c.meaning)}</td></tr>`).join('');$('csv-columns').dataset.ready='1'}
bind('csv-preview',async()=>{const file=$('csv-file').files[0];if(!file)throw Error('Choose a CSV file.');if(file.size>2000000)throw Error('CSV must be smaller than 2 MB.');
 const r=await send('matrix_csv_preview',{csv:await file.text(),filename:file.name});csvToken=r.token;$('csv-save').hidden=!r.token;
 $('csv-result').innerHTML=(r.errors.length?`<div class="blocked"><strong>${r.errors.length} error(s): fix the file and preview again.</strong><ul>${r.errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul></div>`:`<p class="pass">${r.rows.length} valid test(s).</p>`)+
  (r.warnings.length?`<div class="waiting"><strong>Warnings</strong><ul>${r.warnings.map(e=>`<li>${esc(e)}</li>`).join('')}</ul></div>`:'')+
  (r.rows.length?`<div class="table-wrap"><table><thead><tr><th>Test ID</th><th>Feedback</th><th>Speed · rpm</th><th>Load</th><th>Settle · s</th><th>Speed tol · rpm</th><th>Load tol</th><th>Record · s</th><th>Capture · Hz</th><th>Repeat</th></tr></thead><tbody>${r.rows.map(p=>`<tr><td>${esc(p.test_id)}</td><td>${esc(p.method)}</td><td>${p.rpm}</td><td>${esc(loadText(p))}</td><td>${p.settle_s}</td><td>${p.settle_rpm}</td><td>${p.settle_load} ${p.load_unit==='Nm'?'N·m':'A'}</td><td>${p.duration_s}</td><td>${p.capture_rate_hz??'native'}</td><td>${p.repeat}</td></tr>`).join('')}</tbody></table></div>`:'')});
bind('csv-save',async()=>{if(!csvToken)throw Error('Preview the CSV first.');const r=await send('matrix_csv_save',{token:csvToken});csvToken=null;$('csv-save').hidden=true;await refreshPlans();say(`${r.created} test(s) saved as pending. Nothing has moved.`)});
function pointStatus(p){const item=batchState.items?.find(i=>i.id===p.id);const live=p.id===selectedId&&['settling','capturing','recording','processing'].includes(currentPhase)?(currentPhase==='settling'?'settling':'recording'):null;
 if(item){if(item.state==='running')return live||'settling';if(item.state==='queued')return 'pending';if(item.state==='recorded')return 'completed';if(item.state==='retried')return 'failed';if(item.state==='cancelled')return p.status==='pending'?'pending':'failed';return item.state}
 if(live)return live;return {'awaiting review':'completed',completed:'completed',unsuccessful:'failed','invalid-acquisition':'failed',recording:'recording',processing:'recording'}[p.status]||p.status}
const STATUS_ICON={pending:'○',settling:'◷',recording:'●',completed:'✓',blocked:'⛔',failed:'✕',skipped:'—'};
bind('pause-batch',async()=>{batchState=await send('batch_pause');renderMatrix();say('The current test will finish (settle, record, stop); the sequence then pauses.')});
bind('retry-point',async()=>{if(!selectedId)throw Error('Select the failed test first.');batchState=await send('batch_retry',{id:selectedId});await refreshPlans();say('A new attempt is queued after the failed one. The failed run is kept for review.')});
bind('skip-point',async()=>{if(!selectedId)throw Error('Select a test first.');const reason=$('skip-point-reason').value;if(['running','paused'].includes(batchState.state))batchState=await send('batch_skip',{id:selectedId,reason});else await send('skip',{ids:[selectedId],reason});await refreshPlans();say('Test skipped; the reason is kept with it.')});
bind('plan-check-ready',readiness);
let polls=0;
function showSelected(){const p=plans.find(p=>p.id===selectedId);const text=p?`${p.test_id||p.id.slice(-8)} · ${p.method} · ${p.rpm} rpm · ${loadText(p)} · ${p.test_type} · repeat ${p.repeat} · ${p.duration_s} s · ${p.status}`:'Select a pending test point in the test matrix.';$('selected-plan').textContent=text;$('matrix-selected').textContent=text}
function boardReport(role,b,fresh){const state=b.connected?(fresh?b.state:'STALE DATA'):'DISCONNECTED';const description=`${state} · ${b.serial||'no board'} · ${b.feedback_method||b.feedback||'feedback Unavailable'}`;$(role+'-monitor-state').textContent=description;$(role+'-monitor-state').className=b.connected&&fresh?'pass':'waiting';
 const age=Number.isFinite(lastStatus?.telemetry_age_s)?(lastStatus.telemetry_age_s*1000).toFixed(0)+' ms':'Unavailable';const c=b.configuration||{};
 $(role+'-monitor-detail').innerHTML=`<table class="kv"><tbody>${kvRows([['Connection',b.connected?'connected':'disconnected',!b.connected],['Axis state',b.connected?b.state:'Unavailable'],['Feedback mode',b.feedback_method||'Unavailable'],['Control mode',named(CONTROL_MODES,c['axis0.controller.config.control_mode'])],['Data age',fresh?age:'stale or unavailable',!fresh],['Polling',`requested ${lastStatus?.hardware?.profile?.polling_hz??'?'} Hz · observed ${Number.isFinite(lastStatus?.actual_hz)?lastStatus.actual_hz.toFixed(1)+' Hz':'Unavailable'}`],['Units','V, A, rpm, mechanical rev, N·m (estimate)']])}</tbody></table>${faultList(b)}`;
 $(role+'-board-state').innerHTML=`<p class="${b.connected&&fresh?'pass':'waiting'}">${esc(description)}</p><p>Firmware: ${esc(b.firmware||'Unavailable')}<br>Active errors: ${esc((typeof b.errors==='object'?b.errors?.active_errors:b.errors)??'Unavailable')}<br>Disarm reason: ${esc(b.errors?.disarm_reason??b.disarm_reason??'Unavailable')}</p><small>High-rate capture: ${esc(b.capture?.available?b.capture.sample_rate_hz+' samples/s · '+b.capture.samples+' samples per buffer':b.capture?.detail||'Connect to check compatibility')}.<br>${Object.values(b.signals).filter(Number.isFinite).length} readable signals. Board read time: ${Number.isFinite(b.read_end_s)&&Number.isFinite(b.read_start_s)?((b.read_end_s-b.read_start_s)*1000).toFixed(1)+' ms':'Unavailable'}.</small>`}
let lastStatus=null;
async function poll(){try{const d=await get('/api/status');lastStatus=d;const h=d.hardware;lastHardware=h;selectedId=d.selected;batchState=d.batch||{state:'idle',items:[]};currentPhase=d.run_phase;renderMatrix();if(!profileLoaded)fillProfile(h.profile);
const fresh=Number.isFinite(d.telemetry_age_s)&&d.telemetry_age_s<1;
$('live-state').textContent=`${d.state} · ${d.recording?'RECORDING':d.run_phase==='settling'?'SETTLING':'not recording'} · real boards`;
$('package-status').textContent=h.package_installed?`ODrive Python package ${h.package_version} installed.`:'ODrive Python package unavailable. Follow the local setup guide.';
for(const role of ['test','load']){boardReport(role,h.boards[role],fresh);if(!fresh)h.boards[role].signals={}}
$('settling').textContent=d.settled?'Settled at selected conditions':'Waiting for selected conditions to settle';$('settling').className=d.settled?'pass':'waiting';
$('record-state').textContent=`${d.recording?'RECORDING':'Not recording'} · target ${d.requested_hz} Hz · observed ${fresh&&Number.isFinite(d.actual_hz)?d.actual_hz.toFixed(1)+' Hz':'unavailable'} · queue ${d.queue_depth} · ${d.run_phase}`;
$('file').textContent=d.file;showSelected();if(d.error)$('error').textContent=d.error;
if(fresh&&h.sample_id!==lastSample){lastSample=h.sample_id;live.push({time_s:h.acquired_at_s,test:{...h.boards.test.signals},load:{...h.boards.load.signals}});live=live.filter(r=>h.acquired_at_s-r.time_s<=120)}
if(!fresh||!Object.values(h.boards).some(b=>b.connected))live=[];if(view==='live')drawLive();if(view==='dashboard')renderDashboard(d,fresh);if(view==='configuration'&&polls%5===0)renderConfiguration(h);
if(lastRecording&&!d.recording){await refreshPlans();if(view==='review')await refreshRuns();say('Recording ended. Raw data is saved for quality review.')}lastRecording=d.recording;
if(++polls%10===0){if(view==='live'||view==='connections'||view==='troubleshoot')await readiness();if(view==='plan')await refreshPlans()}
}catch(e){lastHardware=null;live=[];drawLive();$('live-state').textContent='Dashboard connection lost';for(const role of ['test','load'])$(role+'-monitor-state').textContent='Dashboard connection lost · readings unavailable';$('error').textContent='Dashboard disconnected. The Python controller may still be running; inspect the local application.'}setTimeout(poll,200)}
show(location.hash.slice(1)||'home');
Promise.all([refreshPlans(),refreshRuns()]).catch(showError).finally(poll);
