'use strict';
const $=id=>document.getElementById(id), num=id=>Number($(id).value), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let plans=[],runs=[],editId=null,selectedId=null,view='home',live=[],lastSample=null,lastRecording=false,reviewRows=[],pairedRows=[],derived={},reviewMeta={},aggregateRows=[],profileLoaded=false,lastHardware=null,scripts=[];
const colors=['#79e3bc','#e9c783','#91bfff','#ef9abe'];
async function get(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function send(action,values={}){const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...values})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function bind(id,fn){$(id).addEventListener('click',async()=>{const b=$(id);b.disabled=true;$('error').textContent='';try{await fn()}catch(e){$('error').textContent=e.message}finally{b.disabled=false}})}
function say(text){$('message').textContent=text}
function show(name){if(!$('view-'+name))name='home';view=name;$('page-menu').value=name;history.replaceState(null,'','#'+name);document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+name);if(name==='live'||name==='connections')readiness().catch(showError);if(name==='scripts')loadScripts().catch(showError);if(name==='review')refreshRuns().catch(showError);if(name==='compare')aggregate().catch(showError);window.scrollTo(0,0);drawAll()}
function showError(e){$('error').textContent=e.message}
$('page-menu').addEventListener('change',()=>show($('page-menu').value));
window.addEventListener('hashchange',()=>show(location.hash.slice(1)));
function planForm(){return {method:$('plan-method').value,test_type:$('plan-type').value,rpm:num('plan-rpm'),load_a:num('plan-load'),repeat:num('plan-repeat'),duration_s:num('plan-duration'),settle_rpm:num('plan-tolerance'),settle_load_a:num('plan-load-tolerance'),settle_s:num('plan-hold'),notes:$('plan-notes').value}}
function fillPlan(p){editId=p.id;$('edit-title').textContent='Edit planned run';for(const [id,key]of [['plan-method','method'],['plan-type','test_type'],['plan-rpm','rpm'],['plan-load','load_a'],['plan-repeat','repeat'],['plan-duration','duration_s'],['plan-tolerance','settle_rpm'],['plan-load-tolerance','settle_load_a'],['plan-hold','settle_s'],['plan-notes','notes']])$(id).value=p[key]}
function renderPlans(){const filter=$('plan-filter').value;const counts={};plans.forEach(p=>counts[p.status]=(counts[p.status]||0)+1);$('plan-counts').textContent=plans.length+' planned · '+Object.entries(counts).map(([k,n])=>n+' '+k).join(' · ');$('plan-table').innerHTML=plans.filter(p=>filter==='all'||p.status===filter).map(p=>`<tr class="${p.id===selectedId?'selected-row':''}"><td><input type="checkbox" data-plan="${esc(p.id)}" aria-label="Include ${esc(p.id)}" ${p.selected?'checked':''}></td><td title="${esc(p.id)}">${esc(p.id.slice(-8))}</td><td>${esc(p.method)}</td><td>${p.rpm.toFixed(1)}</td><td>${p.load_a.toFixed(2)}</td><td>${esc(p.test_type)}</td><td>${p.repeat}</td><td><span class="pill">${esc(p.status)}</span><br>${esc(p.reason)}</td><td><button data-use="${esc(p.id)}">Select</button><button data-edit="${esc(p.id)}">Edit</button></td></tr>`).join('')}
async function refreshPlans(){plans=await get('/api/plans');renderPlans()}
$('plan-filter').addEventListener('change',renderPlans);
$('plan-table').addEventListener('change',e=>{if(e.target.dataset.plan){const p=plans.find(p=>p.id===e.target.dataset.plan);p.selected=e.target.checked}});
$('plan-table').addEventListener('click',async e=>{try{if(e.target.dataset.edit){fillPlan(plans.find(p=>p.id===e.target.dataset.edit));window.scrollTo(0,0)}if(e.target.dataset.use){const p=await send('select',{id:e.target.dataset.use});selectedId=p.id;$('mode').value=p.method;$('rpm').value=p.rpm;$('load').value=p.load_a;renderPlans();showSelected();say('Point selected. Run selected test starts this point when board checks pass.')}}catch(err){showError(err)}});
bind('new-plan',()=>{editId=null;$('edit-title').textContent='Add a test';say('Next save adds a new plan.')});
bind('save-plan',async()=>{await send('plan',{...planForm(),...(editId?{id:editId}:{})});await refreshPlans();say('Test saved. Select it to check readiness.')});
bind('generate',async()=>{const result=await send('matrix',{...planForm(),test_type:'steady state',speed_base:num('speed-base'),load_base:num('load-base'),speeds:$('speed-fractions').value.split(',').map(Number),loads:$('load-fractions').value.split(',').map(Number)});await refreshPlans();say(`${result.created} paired plans added. Exclude infeasible points before running.`)});
bind('select-visible',()=>{const f=$('plan-filter').value;plans.forEach(p=>{if(f==='all'||p.status===f)p.selected=true});renderPlans()});
bind('clear-subset',()=>{plans.forEach(p=>p.selected=false);renderPlans()});
bind('save-subset',async()=>{await send('subset',{ids:plans.filter(p=>p.selected).map(p=>p.id)});say('Subset saved.')});
bind('skip-selected',async()=>{await send('skip',{ids:plans.filter(p=>p.selected).map(p=>p.id),reason:$('skip-reason').value});await refreshPlans();say('Skipped plans retained with their reasons.')});
function showChecks(checks){return checks.map(c=>`<div class="quality-item"><strong>${esc(c.name)}</strong> <span class="${esc(c.state)}">${esc(c.state)}</span><br><small>${esc(c.detail)}</small></div>`).join('')}
async function readiness(){const r=await get('/api/readiness');$('readiness').innerHTML=showChecks(r.checks);$('connection-readiness').innerHTML=showChecks(r.hardware.readiness);$('hardware-report').textContent=JSON.stringify(r.hardware,null,2);return r}
bind('check-ready',readiness);
bind('apply',async()=>{await send('start',{rpm:num('rpm'),load_a:num('load'),mode:$('mode').value});say('Start / apply command accepted. Watch both board states and live measurements.')});
for(const id of ['stop','global-stop'])bind(id,async()=>{await send('stop');await refreshPlans();say('Coast stop requested on both boards. Check their reported states.')});
bind('run-test',async()=>{if(!selectedId)throw Error('Select a pending point from the test matrix first.');await send('run_test',{id:selectedId});show('live');say('Selected-point workflow started: settle, record, then coast stop.')});
bind('record',async()=>{await send('record',{allow_unsettled:$('unsettled').checked});await refreshPlans();say('Recording started. It continues independently of this browser.')});
bind('finish',async()=>{await send('end_record');await refreshPlans();await refreshRuns();say('Recording finished; review the acquisition before accepting it.')});

const profileFields={'test-serial':'test_serial','load-serial':'load_serial','max-speed':'max_speed_rpm','max-load':'max_load_a','test-direction':'test_direction','load-direction':'load_direction','poll-rate':'polling_hz','stop-policy':'stop_policy','roles-verified':'roles_verified','units-verified':'axis_units_verified','stop-verified':'stop_policy_verified','sensorless-verified':'sensorless_startup_verified','sensorless-min':'sensorless_min_rpm','encoder-path':'encoder_reference_path','encoder-scale':'encoder_reference_scale_rad','encoder-speed-path':'encoder_speed_path','encoder-speed-scale':'encoder_speed_scale_rpm','encoder-verified':'encoder_reference_verified'};
const numericProfile=new Set(['max-speed','max-load','test-direction','load-direction','poll-rate','sensorless-min','encoder-scale','encoder-speed-scale']);
function fillProfile(p){for(const [id,key] of Object.entries(profileFields)){const el=$(id);if(el.type==='checkbox')el.checked=p[key]===true;else el.value=p[key]??''}profileLoaded=true}
function readProfile(){const p={};for(const [id,key] of Object.entries(profileFields)){const el=$(id);p[key]=el.type==='checkbox'?el.checked:numericProfile.has(id)?(el.value.trim()===''?null:Number(el.value)):el.value.trim()}return p}
bind('save-connection',async()=>{const h=await send('configure_connection',{profile:readProfile()});fillProfile(h.profile);say('Connection profile saved. No board configuration was written.');await readiness()});
bind('connect',async()=>{await send('connect');live=[];lastSample=null;await readiness();say('Boards connected for read-only monitoring. Motion requires Start or Run selected test.')});
bind('disconnect',async()=>{await send('disconnect');live=[];lastSample=null;drawLive();await readiness();say('Board connections released.')});
bind('clear-errors',async()=>{await send('clear_errors');await readiness();say('Error-clear command sent. Check reported board errors before starting.')});
async function loadScripts(){if(!scripts.length){scripts=await get('/api/scripts');$('script-select').innerHTML=scripts.map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join('')}await chooseScript()}
async function chooseScript(){const name=$('script-select').value;if(!name)return;const script=await get('/api/script?name='+encodeURIComponent(name));if($('script-select').value!==name)return;$('script-code').textContent=script.content;$('script-description').textContent=scripts.find(s=>s.name===name)?.description||''}
$('script-select').addEventListener('change',()=>chooseScript().catch(showError));
bind('copy-script',async()=>{await navigator.clipboard.writeText($('script-code').textContent);say('Script copied.')});

const liveSpecs=[{id:'voltage',title:'DC voltage · V',key:'dc_voltage_v',span:1},
{id:'current',title:'DC current estimate · A',key:'dc_current_a',span:.2},
{id:'speed',title:'Rotor speed · rpm',key:'speed_rpm',span:100},
{id:'position',title:'Rotor position · turns',key:'position_turns',span:1},
{id:'torque',title:'Torque estimate · N·m',key:'torque_nm',span:.1}];
const reviewSpecs=[{id:'angle',title:'Electrical-angle error · deg',keys:['angle_error_deg'],labels:['Estimated − independent reference'],span:1},
{id:'phase',title:'Phase currents · A',keys:['ia_a','ib_a','ic_a'],labels:['Ia','Ib','Ic'],span:.2},
{id:'dq',title:'Id / Iq · A',keys:['drive_id_a','drive_iq_a','id_reference_a','iq_reference_a'],labels:['Controller Id','Controller Iq','Encoder-reference Id','Encoder-reference Iq'],span:.2},
{id:'rpm',title:'Speed · rpm',keys:['encoder_rpm','command_rpm','estimated_rpm'],labels:['Independent encoder','Command','Estimator'],span:100},
{id:'bus',title:'DC bus voltage · V',keys:['drive_dc_voltage_v','load_dc_voltage_v'],labels:['Test','Load'],span:1},
{id:'branch',title:'Branch DC current · A',keys:['drive_dc_current_a','load_dc_current_a'],labels:['Test','Load'],span:.2}];
function chartCards(container,specs,prefix){$(container).innerHTML=specs.map(s=>`<article class="panel"><h2>${s.title}</h2><div class="legend">${s.labels.map((l,i)=>`<span style="color:${colors[i]}">${l} <b id="${prefix}-${s.id}-${i}" class="metric-value"></b></span>`).join('')}</div><canvas id="${prefix}-${s.id}" aria-label="${s.title}"></canvas></article>`).join('')}
for(const role of ['test','load'])chartCards(role+'-live-charts',liveSpecs.map(s=>({...s,labels:[role==='test'?'Test motor':'Load motor']})),role);
chartCards('review-charts',reviewSpecs,'review');
function chart(id,series,minSpan,range,windowRange){const c=$(id);if(!c||c.clientWidth<1)return;const g=c.getContext('2d'),w=c.clientWidth,h=240,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;g.setTransform(dpr,0,0,dpr,0,0);const left=62,right=w-12,top=16,bottom=h-32;let values=[];for(const s of series)for(const p of s.points)if(Number.isFinite(p.y))values.push(p.y);if(!values.length){g.fillStyle='#aabcc8';g.font='14px system-ui';g.fillText('Channel unavailable in this dataset',15,100);return}let low=values.reduce((a,b)=>Math.min(a,b),Infinity),high=values.reduce((a,b)=>Math.max(a,b),-Infinity),span=Math.max(minSpan,high-low),mid=(high+low)/2;low=mid-span*.6;high=mid+span*.6;let lo=range[0],hi=range[1];if(hi<=lo)hi=lo+1;const x=t=>left+(t-lo)/(hi-lo)*(right-left),y=v=>bottom-(v-low)/(high-low)*(bottom-top);g.font='11px system-ui';g.textAlign='right';g.fillStyle='#aabcc8';for(let i=0;i<=4;i++){let v=low+(high-low)*i/4,py=y(v);g.strokeStyle='#344b59';g.beginPath();g.moveTo(left,py);g.lineTo(right,py);g.stroke();g.fillText(Math.abs(v)>=100?v.toFixed(0):v.toFixed(2),left-8,py+4)}g.textAlign='center';for(let i=0;i<=3;i++){const t=lo+(hi-lo)*i/3;g.fillText(t.toFixed(2)+' s',x(t),bottom+22)}g.save();g.beginPath();g.rect(left,top,right-left,bottom-top);g.clip();if(windowRange){g.fillStyle='#79e3bc13';g.fillRect(x(windowRange[0]),top,x(windowRange[1])-x(windowRange[0]),bottom-top);g.strokeStyle='#79e3bc';for(const t of windowRange){g.beginPath();g.moveTo(x(t),top);g.lineTo(x(t),bottom);g.stroke()}}
for(const s of series){g.strokeStyle=s.color;g.lineWidth=1.6;g.setLineDash(s.dash||[]);g.beginPath();let last=null;const dt=s.points.length>1?(s.points[s.points.length-1].t-s.points[0].t)/(s.points.length-1):1;for(const p of s.points){if(!Number.isFinite(p.y)){last=null;continue}if(last!==null&&p.t-last<Math.max(dt*2.5,.0001))g.lineTo(x(p.t),y(p.y));else g.moveTo(x(p.t),y(p.y));last=p.t}g.stroke()}g.restore()}
function drawLive(){const end=live.length?live[live.length-1].time_s:0;for(const [i,role] of ['test','load'].entries())for(const spec of liveSpecs){const board=lastHardware?.boards[role];const available=board?.connected&&Number.isFinite(board.signals[spec.key]);const points=available?live.map(r=>({t:r.time_s-end,y:r[role]?.[spec.key]})):[];chart(role+'-'+spec.id,[{color:colors[i],points}],spec.span,[-30,0]);const label=$(role+'-'+spec.id+'-0');label.style.color=colors[i];label.textContent=available?board.signals[spec.key].toFixed(2):'unavailable'}}
function drawReview(){if(!reviewRows.length)return;const t=reviewRows.map(r=>r.time_s);for(const spec of reviewSpecs){const series=spec.keys.map((key,i)=>({color:colors[i],points:derived[key]?derived.time_s.map((x,j)=>({t:x,y:derived[key][j]})):reviewRows.map(r=>({t:r.time_s,y:r[key]}))}));if(pairedRows.length){const offset=reviewRows[0].time_s-pairedRows[0].time_s;spec.keys.forEach((key,i)=>series.push({color:colors[i],dash:[5,5],points:pairedRows.map(r=>({t:r.time_s+offset,y:r[key]}))}))}chart('review-'+spec.id,series,spec.span,[t.reduce((a,b)=>Math.min(a,b),Infinity),t.reduce((a,b)=>Math.max(a,b),-Infinity)],[num('window-start'),num('window-end')])}}
function drawAll(){if(view==='live')drawLive();if(view==='review')drawReview()}
window.addEventListener('resize',drawAll);for(const id of ['window-start','window-end'])$(id).addEventListener('input',drawReview);

async function refreshRuns(){runs=await get('/api/runs');const old=$('review-run').value;$('review-run').innerHTML=runs.map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(-8))} · ${esc(r.plan.method)} · ${r.plan.rpm} rpm / ${r.plan.load_a} A · repeat ${r.plan.repeat} · ${esc(r.status)}</option>`).join('');if(runs.some(r=>r.id===old))$('review-run').value=old;await chooseRun()}
async function chooseRun(){const id=$('review-run').value;if(!id)return;const run=await get('/api/run?id='+encodeURIComponent(id));const old=$('review-dataset').value;$('review-dataset').innerHTML='<option value="telemetry">Continuous telemetry</option>'+run.datasets.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');$('review-dataset').value=run.datasets.includes(old)?old:(run.datasets[0]||'telemetry');$('run-metadata').textContent=JSON.stringify(run,null,2);$('download').href='/download?id='+encodeURIComponent(id);$('paired-run').innerHTML='<option value="">None</option>'+runs.filter(r=>r.id!==id&&r.plan.rpm===run.plan.rpm&&r.plan.load_a===run.plan.load_a&&r.plan.repeat===run.plan.repeat&&r.plan.method!==run.plan.method&&r.plan.test_type===run.plan.test_type&&r.status!=='recording').map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(-8))} · ${esc(r.plan.method)} · ${esc(r.source)}</option>`).join('');$('window-type').value=run.plan.test_type==='steady state'?'steady state':'transient';if(run.latest_review)renderResult(run.latest_review.summary);else{$('quality').textContent='No analysis yet.';$('metrics').innerHTML=''}reviewRows=[];pairedRows=[];derived={};for(const s of reviewSpecs){const c=$('review-'+s.id);c.getContext('2d').clearRect(0,0,c.width,c.height)}}
$('review-run').addEventListener('change',()=>chooseRun().catch(showError));bind('refresh-runs',refreshRuns);
async function loadData(){const data=await get('/api/data?id='+encodeURIComponent($('review-run').value)+'&dataset='+encodeURIComponent($('review-dataset').value));reviewRows=data.rows;reviewMeta=data.metadata;pairedRows=[];derived={};if(!reviewRows.length)throw Error('Dataset is empty.');$('window-start').value=reviewRows[0].time_s;$('window-end').value=reviewRows[reviewRows.length-1].time_s;$('dataset-info').textContent=`${data.original_samples} raw samples · display every ${data.display_stride} sample(s) · ${data.metadata.source} · ${data.metadata.acquisition.source}. Time is this dataset's original clock.`;$('overlay-info').textContent='Overlay clocks are not assumed synchronized.';drawReview()}
bind('load-data',loadData);
function settings(){return {start_s:num('window-start'),end_s:num('window-end'),window_type:$('window-type').value,max_timing_angle_deg:num('timing-budget'),...($('fundamental').value?{fundamental_hz:num('fundamental')}:{})}}
function renderResult(result){$('quality').innerHTML=`<p class="${result.valid_acquisition?'pass':'error'}">${result.valid_acquisition?'Acquisition checks passed for this window':'Acquisition checks failed or insufficient data'}</p>`+(result.quality_flags||[]).map(f=>`<div class="quality-item ${esc(f.severity)}">${esc(f.message)}</div>`).join('');const timing=result.timing||{};$('metrics').innerHTML=`<tr><th>Actual mean sample rate</th><td>${timing.actual_mean_hz?.toFixed(2)??'unavailable'} Hz</td></tr><tr><th>Timing gaps</th><td>${timing.gap_count??'unavailable'}</td></tr>`+Object.entries(result.metrics||{}).map(([key,val])=>`<tr><th>${esc(key)}</th><td>${esc(typeof val==='object'?JSON.stringify(val):val)}</td></tr>`).join('')}
bind('analyze',async()=>{const result=await send('review',{run_id:$('review-run').value,dataset:$('review-dataset').value,settings:settings()});renderResult(result);derived=result.derived||{};drawReview();say('Analysis saved as a new revision; raw data unchanged.')});
bind('overlay',async()=>{const id=$('paired-run').value;if(!id){pairedRows=[];drawReview();return}if(!reviewRows.length)throw Error('Load the primary dataset first.');const other=await get('/api/run?id='+encodeURIComponent(id));const dataset=$('review-dataset').value==='telemetry'?'telemetry':other.datasets.find(d=>d.startsWith('capture_'));if(!dataset)throw Error('Paired run has no matching capture type.');const data=await get('/api/data?id='+encodeURIComponent(id)+'&dataset='+encodeURIComponent(dataset));pairedRows=data.rows;$('overlay-info').textContent='Dashed: paired run, aligned by each dataset start for comparison only. This is not clock synchronization. Primary shaded window and metrics apply only to the primary run.';drawReview()});
bind('retry',async()=>{const p=await send('repeat',{run_id:$('review-run').value});await refreshPlans();selectedId=p.id;$('mode').value=p.method;$('rpm').value=p.rpm;$('load').value=p.load_a;say('New attempt planned with the same repeat number. Earlier attempts remain intact.');show('live')});
bind('save-note',async()=>{await send('note',{run_id:$('review-run').value,note:$('review-note').value});say('Note appended to the event log.')});
bind('accept',async()=>{await send('accept',{run_id:$('review-run').value,outcome:$('outcome').value,reason:$('review-note').value});await refreshPlans();await refreshRuns();say('Review saved. Next selected pending plan is ready for manual application.')});
$('mapping').value=JSON.stringify({time_s:{column:'Time',unit:'s',scale:1,offset:0,kind:'measured'},ia_a:{column:'Ia',unit:'A',scale:1,offset:0,kind:'measured'},ib_a:{column:'Ib',unit:'A',scale:1,offset:0,kind:'measured'},ic_a:{column:'Ic',unit:'A',scale:1,offset:0,kind:'measured'}},null,2);
$('import-meta').value=JSON.stringify({instrument:'',calibration_id:'',acquisition:{requested_hz:null,bandwidth_hz:null,filtering:'',anti_alias_verified:false,switching_hz:null,ranges:{},synchronization:{method:'',simultaneous:false,uncertainty_s:null}},calibration:{verified:false,id:'',pole_pairs:null,offset_rad:null,encoder_direction:1},independent_encoder_provenance:'',device_serials:{test:null,load:null},firmware:null},null,2);
bind('import',async()=>{const file=$('import-file').files[0];if(!file)throw Error('Choose a CSV file.');if(file.size>8000000)throw Error('CSV must be smaller than 8 MB.');const result=await send('import',{run_id:$('review-run').value,source:$('import-source').value,csv:await file.text(),mapping:JSON.parse($('mapping').value),metadata:JSON.parse($('import-meta').value)});await chooseRun();$('review-dataset').value=result.dataset;await loadData();say('Original CSV, normalized channels and provenance saved.')});
async function aggregate(){aggregateRows=await get('/api/aggregate?metric='+encodeURIComponent($('aggregate-metric').value));$('aggregate-table').innerHTML=aggregateRows.map((r,i)=>`<tr><td>${esc(r.source)}</td><td>${esc(r.method)}</td><td>${r.rpm}</td><td>${r.load_a}</td><td>${r.n}</td><td>${r.mean.toPrecision(5)}</td><td>${r.std===null?'Requires another repeat':r.std.toPrecision(4)}</td><td>${i+1}</td></tr>`).join('')||'<tr><td colspan="8">No compatible completed analyses for this metric.</td></tr>';const groups={};for(const r of aggregateRows){const key=JSON.stringify([r.source,r.method,r.test_type,r.group_signature]);(groups[key]??=[]).push(r)}let html='';for(const rows of Object.values(groups)){const speeds=[...new Set(rows.map(r=>r.rpm))].sort((a,b)=>a-b),loads=[...new Set(rows.map(r=>r.load_a))].sort((a,b)=>a-b);if(speeds.length<2||loads.length<2||rows.filter(r=>r.n>=2).length<4){html+=`<p>${esc(rows[0].source+' · '+rows[0].method)}: insufficient coverage for a map (need four cells with ≥2 independent repeats spanning two speeds and two loads).</p>`;continue}const max=Math.max(...rows.map(r=>r.mean),.000001);html+=`<div class="map table-wrap"><h3>${esc(rows[0].source+' · '+rows[0].method)}</h3><table><thead><tr><th>rpm / A</th>${loads.map(l=>`<th>${l} A</th>`).join('')}</tr></thead><tbody>${speeds.map(s=>`<tr><th>${s} rpm</th>${loads.map(l=>{const r=rows.find(r=>r.rpm===s&&r.load_a===l);return r&&r.n>=2?`<td style="background:rgba(66,160,133,${.1+.6*r.mean/max})">${r.mean.toPrecision(4)}<br><small>n=${r.n}</small></td>`:'<td>Insufficient data</td>'}).join('')}</tr>`).join('')}</tbody></table></div>`}$('maps').innerHTML=html||'<p>Maps appear after sufficient valid repeat coverage.</p>'}
bind('aggregate',aggregate);
let polls=0;
function showSelected(){const p=plans.find(p=>p.id===selectedId);const text=p?`${p.method} · ${p.rpm} rpm · ${p.load_a} A · ${p.test_type} · repeat ${p.repeat} · ${p.duration_s} s · ${p.status}`:'Select a pending test point in the test matrix.';$('selected-plan').textContent=text;$('matrix-selected').textContent=text}
function boardReport(role,b,fresh){const state=b.connected?(fresh?b.state:'STALE DATA'):'DISCONNECTED';const description=`${state} · ${b.serial||'no board'} · ${b.feedback_method||b.feedback||'feedback unavailable'}`;$(role+'-monitor-state').textContent=description;$(role+'-board-state').innerHTML=`<p class="${b.connected&&fresh?'pass':'waiting'}">${esc(description)}</p><p>Firmware: ${esc(b.firmware||'unavailable')}<br>Active errors: ${esc((typeof b.errors==='object'?b.errors?.active_errors:b.errors)??'unavailable')}<br>Disarm reason: ${esc(b.errors?.disarm_reason??b.disarm_reason??'unavailable')}</p><small>${Object.values(b.signals).filter(Number.isFinite).length} readable signals. Board read time: ${Number.isFinite(b.read_end_s)&&Number.isFinite(b.read_start_s)?((b.read_end_s-b.read_start_s)*1000).toFixed(1)+' ms':'unavailable'}.</small>`}
async function poll(){try{const d=await get('/api/status');const h=d.hardware;lastHardware=h;selectedId=d.selected;if(!profileLoaded)fillProfile(h.profile);
const fresh=Number.isFinite(d.telemetry_age_s)&&d.telemetry_age_s<1;
$('live-state').textContent=`${d.state} · ${d.recording?'RECORDING':d.run_phase==='settling'?'SETTLING':'not recording'} · real boards`;
$('package-status').textContent=h.package_installed?`ODrive Python package ${h.package_version} installed.`:'ODrive Python package unavailable. Follow the local setup guide.';
for(const role of ['test','load']){boardReport(role,h.boards[role],fresh);if(!fresh)h.boards[role].signals={}}
$('settling').textContent=d.settled?'Settled at selected conditions':'Waiting for selected conditions to settle';$('settling').className=d.settled?'pass':'waiting';
$('record-state').textContent=`${d.recording?'RECORDING':'Not recording'} · target ${d.requested_hz} Hz · observed ${fresh&&Number.isFinite(d.actual_hz)?d.actual_hz.toFixed(1)+' Hz':'unavailable'} · queue ${d.queue_depth} · ${d.run_phase}`;
$('file').textContent=d.file;showSelected();if(d.error)$('error').textContent=d.error;
if(fresh&&h.sample_id!==lastSample){lastSample=h.sample_id;live.push({time_s:h.acquired_at_s,test:{...h.boards.test.signals},load:{...h.boards.load.signals}});live=live.filter(r=>h.acquired_at_s-r.time_s<=30)}
if(!fresh||!Object.values(h.boards).some(b=>b.connected))live=[];if(view==='live')drawLive();
if(lastRecording&&!d.recording){await refreshPlans();if(view==='review')await refreshRuns();say('Recording ended. Raw data is saved for quality review.')}lastRecording=d.recording;
if(++polls%10===0&&(view==='live'||view==='connections'))await readiness();
}catch(e){lastHardware=null;live=[];drawLive();$('live-state').textContent='Dashboard connection lost';for(const role of ['test','load'])$(role+'-monitor-state').textContent='Dashboard connection lost · readings unavailable';$('error').textContent='Dashboard disconnected. The Python controller may still be running; inspect the local application.'}setTimeout(poll,200)}
show(location.hash.slice(1)||'home');
Promise.all([refreshPlans(),refreshRuns()]).catch(showError).finally(poll);
